SUBROUTINE LINMINAIM(P,XI,FRET)

USE commondata, ONLY: num,tolaim
USE cgdata, ONLY: PCOMAIM,XICOMAIM

IMPLICIT NONE

INTEGER :: J
DOUBLE PRECISION, DIMENSION(num*10), INTENT(INOUT) :: P,XI
DOUBLE PRECISION, INTENT(OUT) :: FRET
DOUBLE PRECISION :: AXX,BXX,XX,FA,FX,FB,XMIN,BRENT,DBRENT,F1DIMAIM
EXTERNAL F1DIMAIM,DF1DIMAIM

PCOMAIM=P
XICOMAIM=XI
AXX=0.000d0
XX=0.001d0
BXX=0.002d0
CALL MNBRAKAIM(AXX,XX,BXX,FA,FX,FB)
FRET=DBRENT(AXX,XX,BXX,F1DIMAIM,DF1DIMAIM,TOLAIM,XMIN)
!     FRET=BRENT(AXX,XX,BXX,F1DIMAIM,TOLAIM,XMIN)
XI=XMIN*XI
P=P+XI

RETURN
END SUBROUTINE
